### ISSUE TITLE
[Feature Request]: Improve Navbar Icon Design and Button Order

### ISSUE THREAD

**Issue by Rucha-Ambaliya** [Varsha-1605/SocioSell#3]
### 🎯 Problem to Solve

The current navbar in index.html contains three buttons: **Upload, Search,** and **Video**. To enhance clarity and user experience, the following changes are proposed:

1. Icon Change for "Upload":

**Replace** the **Upload** **icon** with an **image** **icon** to better reflect its functionality of generating a product listing via image uploads.

This change aims to reduce potential confusion between the **Upload** and **Video** buttons.

### 🎨 Feature Category

🎨 User Interface

### Request

Please assign **labels Assigned** and **SWOC** to this issue for tracking and recognition.

### Branch Name

I plan to name the branch for this issue as:
**feature/update-navbar-image-icon**

If any changes to this naming format are required, please let me know to avoid confusion and ensure consistency with project standards.

### 📜 Confirmation

- [X] I have searched for similar feature requests
- [X] This feature aligns with SocioSell's purpose

**Comment by Varsha-1605** [comment]
kindly raise this issue on 1st january then only  it will be counted.

**Comment by Rucha-Ambaliya** [comment]
Okay, I thought if pr is done after 1st of January it would be counted, I will mark it complete then...

**Comment by Rucha-Ambaliya** [comment]
Okay, I thought the PR would be counted if completed after the 1st of January. I'll mark it as complete for now then.

**Comment by Rucha-Ambaliya** [comment]
Okay, I thought the PR would be counted if completed after the 1st of January. I have marked it as complete for now then.

**Comment by Rucha-Ambaliya** [comment]
Good morning ma'am!

should I reopen this issue or create a new one?

**Comment by Varsha-1605** [comment]
sure @Rucha-Ambaliya !
